# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_tmprotein_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmhelixtriplet',
            name='Score',
            field=models.FloatField(null=True),
        ),
    ]
