# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_tmhelixtriplet_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmprotein',
            name='Set',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
