# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_tmprotein_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmhelixtriplet',
            name='Set',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
