# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20160602_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file',
            field=models.FileField(upload_to=b'PDBs'),
        ),
    ]
