# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubMedId', models.CharField(max_length=200, null=True)),
                ('authors', models.CharField(max_length=200, null=True)),
                ('year', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('journal', models.CharField(max_length=200, null=True)),
                ('volume', models.CharField(max_length=200, null=True)),
                ('issue', models.CharField(max_length=200, null=True)),
                ('pages', models.CharField(max_length=200, null=True)),
                ('doi', models.CharField(max_length=200, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_parser.group')),
            ],
        ),
        migrations.CreateModel(
            name='structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdbCode', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('species', models.CharField(max_length=200, null=True)),
                ('taxonomicDomain', models.CharField(max_length=200, null=True)),
                ('expressedInSpecies', models.CharField(max_length=200, null=True)),
                ('resolution', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('Type', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_parser.group')),
            ],
        ),
    ]
