# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0003_auto_20160609_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='species',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='protein',
            name='taxonomicDomain',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
