# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0004_auto_20160609_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
