# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0009_auto_20160609_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='authors',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='journal',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='pages',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='bibliography',
            name='title',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
