# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0010_auto_20160609_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='DatabaseModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xml_parser.DatabaseModel'),
        ),
        migrations.AddField(
            model_name='protein',
            name='chain',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='DatabaseModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xml_parser.DatabaseModel'),
        ),
    ]
