# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0011_auto_20160706_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='Path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
