# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0012_structure_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='Chain',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='Path',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
