# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0013_auto_20160708_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='Processed',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
