# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0020_remove_structure_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='Processed',
            field=models.NullBooleanField(),
        ),
    ]
