# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0022_auto_20160708_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='DatabaseModel',
        ),
        migrations.AddField(
            model_name='structure',
            name='DatabaseModel',
            field=models.ManyToManyField(to='xml_parser.DatabaseModel'),
        ),
    ]
