# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0023_auto_20160715_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasemodel',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
