# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=200)),
                ('Atom_ID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Residue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TMHelixModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TMHelix_ID', models.CharField(max_length=200)),
                ('TMHelix_AASEQ', models.CharField(max_length=200)),
                ('TMHelix_Tilt', models.FloatField(null=True)),
                ('TMHelix_Tilt_EC', models.FloatField(null=True)),
                ('TMHelix_Tilt_IC', models.FloatField(null=True)),
                ('TMHelix_KinkAngle', models.FloatField(null=True)),
                ('TMHelix_Overhang', models.FloatField(null=True)),
                ('TMHelix_pdb_path', models.CharField(max_length=200)),
                ('Atoms', models.TextField(default=b'fejslik', null=True)),
                ('MainAxis_X', models.FloatField(null=True)),
                ('MainAxis_Y', models.FloatField(null=True)),
                ('MainAxis_Z', models.FloatField(null=True)),
                ('ECAxis_X', models.FloatField(null=True)),
                ('ECAxis_Y', models.FloatField(null=True)),
                ('ECAxis_Z', models.FloatField(null=True)),
                ('ICAxis_X', models.FloatField(null=True)),
                ('ICAxis_Y', models.FloatField(null=True)),
                ('ICAxis_Z', models.FloatField(null=True)),
                ('MC_EC_X', models.FloatField(null=True)),
                ('MC_EC_Y', models.FloatField(null=True)),
                ('MC_EC_Z', models.FloatField(null=True)),
                ('MC_MM_X', models.FloatField(null=True)),
                ('MC_MM_Y', models.FloatField(null=True)),
                ('MC_MM_Z', models.FloatField(null=True)),
                ('MC_IC_X', models.FloatField(null=True)),
                ('MC_IC_Y', models.FloatField(null=True)),
                ('MC_IC_Z', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMHelixPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrossingAngle', models.FloatField(null=True)),
                ('CrossingAngleEC', models.FloatField(null=True)),
                ('CrossingAngleIC', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMHelixTriplet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phi', models.FloatField(null=True)),
                ('Score', models.FloatField(null=True)),
                ('Set', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TMProtein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TMProtein_ID', models.CharField(max_length=200)),
                ('tmproteinfile', models.FileField(upload_to=myapp.models.get_upload_path)),
                ('path', models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path)),
                ('Atoms', models.TextField(default=b'fejslik', null=True)),
                ('Score', models.FloatField(null=True)),
                ('Set', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tmhelixtriplet',
            name='TMProtein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMProtein'),
        ),
        migrations.AddField(
            model_name='tmhelixpair',
            name='TMProtein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMProtein'),
        ),
        migrations.AddField(
            model_name='tmhelixmodel',
            name='TMHelixPair',
            field=models.ManyToManyField(to='myapp.TMHelixPair'),
        ),
        migrations.AddField(
            model_name='tmhelixmodel',
            name='TMHelixTriplet',
            field=models.ManyToManyField(to='myapp.TMHelixTriplet'),
        ),
        migrations.AddField(
            model_name='tmhelixmodel',
            name='TMProtein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMProtein'),
        ),
        migrations.AddField(
            model_name='atom',
            name='TMHelixModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMHelixModel'),
        ),
        migrations.AddField(
            model_name='atom',
            name='TMProtein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMProtein'),
        ),
    ]
