# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atom',
            name='Mass',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='atom',
            name='Residue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Residue'),
        ),
        migrations.AddField(
            model_name='atom',
            name='X',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='atom',
            name='Y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='atom',
            name='Z',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='residue',
            name='Z',
            field=models.FloatField(null=True),
        ),
    ]
