# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160606_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='AAThreeLetter',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
