# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_atom_aathreeletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='Residue_ID',
            field=models.CharField(default=datetime.datetime(2016, 6, 6, 19, 59, 3, 456153, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
