# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_residue_residue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='residue',
            name='TMHelixModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.TMHelixModel'),
        ),
    ]
