# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_residue_tmhelixmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmhelixtriplet',
            name='Type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
