# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tmhelixtriplet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='XLSFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsfile', models.FileField(upload_to=myapp.models.get_upload_path)),
                ('path', models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path)),
                ('TMProtein_ID', models.CharField(max_length=200)),
            ],
        ),
    ]
