# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20160706_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmprotein',
            name='tmproteinfile',
            field=models.FileField(null=True, upload_to=myapp.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='path',
            field=models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='xlsfile',
            field=models.FileField(upload_to=myapp.models.get_upload_path),
        ),
    ]
