# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20160717_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustering',
            name='distance',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='clustering',
            name='idx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clustering',
            name='no_cluster',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='path',
            field=models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='xlsfile',
            field=models.FileField(upload_to=myapp.models.get_upload_path),
        ),
    ]
