# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_auto_20160717_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='Clustering',
            field=models.ManyToManyField(null=True, to='myapp.Clustering'),
        ),
        migrations.AddField(
            model_name='tmhelixtriplet',
            name='Cluster',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='path',
            field=models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='xlsfile',
            field=models.FileField(upload_to=myapp.models.get_upload_path),
        ),
    ]
