# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_parser', '0023_auto_20160715_2010'),
        ('myapp', '0050_auto_20160728_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='DatabaseModel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='xml_parser.DatabaseModel'),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='path',
            field=models.CharField(max_length=200, verbose_name=myapp.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='xlsfile',
            name='xlsfile',
            field=models.FileField(upload_to=myapp.models.get_upload_path),
        ),
    ]
